config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  devise_for :users
  root 'users#home'
  get '/add_friendship' => 'friendships#add_friendship' 
  get '/accept_friendship' => 'friendships#accept_friendship'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :friendships
         has_many :friends, -> { where(friendships: { status: "accepted"}) }, :through => :friendships
         # has_many :requested_friends, :through => :friendships, :source => :friend, :conditions => "status = 'requested'", :order => :created_at
		 # has_many :pending_friends, :through => :friendships, :source => :friend, :conditions => "status = 'pending'", :order => :created_at

		 # has_many :requested_friends,->{where(friendships:{status: "accepted"})},:through => :friendships
		 # has_many :pending_friends,:source => :friend, :through => :friendships

		 has_many :got_request_friendships, -> { where(friendships: { status: "pending" }) }, class_name: 'Friendship', foreign_key: :friend_id
		 # has_many :requested_friendships, through: :got_request_friendships, source: :friend
     has_many :requested_friendships, -> { where(friendships: { status: "pending" }) }, class_name: 'Friendship', foreign_key: :user_id
end



# has_many :user_friendships
# has_many :friends, -> { where(user_friendships: { state: "accepted"}) }, through: :user_friendships
# has_many :pending_user_friendships, -> { where { state: "pending" } }, class_name: 'UserFriendship', foreign_key: :user_id                                  
# has_many :pending_friends, through: :pending_user_friendships, source: :friend

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  # def index
  #   @friendships = Friendship.all
  # end

  # GET /friendships/1
  # GET /friendships/1.json
  # def show
  # end

  # GET /friendships/new
  # def new
  #   @friendship = Friendship.new
  # end

  # GET /friendships/1/edit
  # def edit
  # end

  # POST /friendships
  # POST /friendships.json
  # def create
  #   @friendship = Friendship.new(friendship_params)

  #   respond_to do |format|
  #     if @friendship.save
  #       format.html { redirect_to @friendship, notice: 'Friendship was successfully created.' }
  #       format.json { render :show, status: :created, location: @friendship }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @friendship.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  # def update
  #   respond_to do |format|
  #     if @friendship.update(friendship_params)
  #       format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @friendship }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @friendship.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  # def destroy
  #   @friendship.destroy
  #   respond_to do |format|
  #     format.html { redirect_to friendships_url, notice: 'Friendship was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  def add_friendship
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id].to_i,:status => "pending")
    @friendship.save
  end

  def accept_friendship
    @friendship = Friendship.where(:id => "#{params["friendship"].to_i}").first
    @friendship.update_attributes(:status => "accepted")
    Friendship.new(:user_id => @friendship.friend_id ,:friend_id => @friendship.user_id,:status => "accepted" ).save 
     
    redirect_to root_path

  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def home
		@users = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="field">
    <%= f.label :is_friends %><br>
    <%= f.number_field :is_friends %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th>Is friends</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= friendship.is_friends %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Is friends:</strong>
  <%= @friendship.is_friends %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
	Signed in as <%= current_user.email %>. Not you?
		<%= link_to "Sign out", destroy_user_session_path,:method => :delete %>
	<% else %>
		<%= link_to "Sign up", new_user_registration_path  %> 
		<%= link_to "Sign in", new_user_session_path %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/users/home.html.erb
<%@users.each do |user|%>
<% if current_user != user %>
	<p><%=user.email%>(<%=link_to "send_request",add_friendship_path(:friend_id => user.id )%>)</p>
<%end%>
<%end%>


<% if current_user.present? %>
<h1>Friends List  </h1>
<%current_user.friends.each do |friendships| %>
<p><%= friendships.email %></p>
<%end%>

<h1> I got request</h1>
<%current_user.got_request_friendships.each do |friendships|%>
<p><%= friendships.user.email%></p>(<%= link_to "accept",accept_friendship_path(:friendship => friendships)%>)
<%end%>
<h1>I send request</h1>
<%current_user.requested_friendships.each do |friendships|%>
<p><%= friendships.friend.email%></p>
<%end%>
<%end%>